version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "nuget"
    reviewers:
      - "Thuyen21"
  - package-ecosystem: "github-actions"
    # Files stored in `app` directory
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "github-actions"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "npm"
    pull-request-branch-name:
      separator: "-"
