version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "nuget"
    open-pull-requests-limit: 99

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "github-actions"
    open-pull-requests-limit: 99

  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   labels:
  #     - "npm"
