version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "nuget"

  - package-ecosystem: "github-actions"
    # Files stored in `app` directory
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "github-actions"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "npm"
