// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace BlazorMovie.Server.Models
{
    public partial class ContextModel
    {
        partial void Initialize()
        {
            var applicationRole = ApplicationRoleEntityType.Create(this);
            var applicationUser = ApplicationUserEntityType.Create(this);
            var applicationUserRole = ApplicationUserRoleEntityType.Create(this);
            var identityRoleClaimGuid = IdentityRoleClaimGuidEntityType.Create(this);
            var identityUserClaimGuid = IdentityUserClaimGuidEntityType.Create(this);
            var identityUserLoginGuid = IdentityUserLoginGuidEntityType.Create(this);
            var identityUserTokenGuid = IdentityUserTokenGuidEntityType.Create(this);

            ApplicationUserRoleEntityType.CreateForeignKey1(applicationUserRole, applicationRole);
            ApplicationUserRoleEntityType.CreateForeignKey2(applicationUserRole, applicationUser);
            IdentityRoleClaimGuidEntityType.CreateForeignKey1(identityRoleClaimGuid, applicationRole);
            IdentityUserClaimGuidEntityType.CreateForeignKey1(identityUserClaimGuid, applicationUser);
            IdentityUserLoginGuidEntityType.CreateForeignKey1(identityUserLoginGuid, applicationUser);
            IdentityUserTokenGuidEntityType.CreateForeignKey1(identityUserTokenGuid, applicationUser);

            ApplicationRoleEntityType.CreateAnnotations(applicationRole);
            ApplicationUserEntityType.CreateAnnotations(applicationUser);
            ApplicationUserRoleEntityType.CreateAnnotations(applicationUserRole);
            IdentityRoleClaimGuidEntityType.CreateAnnotations(identityRoleClaimGuid);
            IdentityUserClaimGuidEntityType.CreateAnnotations(identityUserClaimGuid);
            IdentityUserLoginGuidEntityType.CreateAnnotations(identityUserLoginGuid);
            IdentityUserTokenGuidEntityType.CreateAnnotations(identityUserTokenGuid);

            AddAnnotation("ProductVersion", "6.0.3");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
