name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/workflows/setup.yml
        with:
          username: ${{ inputs.username }}
          token: ${{ secrets.envPAT }}
      # - name: Build
      #   run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore
