name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    uses: Thuyen21/Blazor-Movie-/.github/workflows/setup.yml@test-action
    with:
      username: crt
      token: crt
  build:
    needs: setup
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@main
      - uses: Thuyen21/Blazor-Movie-@test-action
        with:
          username: ${{ inputs.username }}
          token: ${{ secrets.envPAT }}
      # - name: Build
      #   run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore
