name: Build .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
      # - uses: actions/cache@v2.1.7
      #   with:
      #     path: |
      #       C:\Users\runneradmin\AppData\Local\Microsoft\dotnet
      #     key: ${{ runner.os }}-build-dotnet-6.0.102
      #     restore-keys: |
      #       ${{ runner.os }}-build-dotnet-6.0.102

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-quality: 'preview'

      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install tools
        run: |
          # dotnet workload restore
          # dotnet workload install maui wasm-tools
          dotnet workload install android ios maccatalyst tvos macos maui wasm-tools

      - name: Restore dependencies
        run: dotnet restore
      # - name: Build
      #   run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore
