name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: Thuyen21/Blazor-Movie-/.github/workflows/setup.yml@test-action
      # - name: Build
      #   run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore
