name: .NET

on:
  workflow_call:

jobs:
  build:
    needs: setup
    runs-on: windows-2022
    steps:
      # - name: Build
      #   run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore
