name: .NET

on:
  push:
    branches: [ Publish  ]
  pull_request:
    branches: [ Publish  ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.2.3
      with:
        dotnet-version: 6
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish BlazorApp3.sln -c Release -o release –nologo
