name: Build .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/cache@v2.1.7
        with:
          path: |
            C:\Users\runneradmin\AppData\Local\Microsoft\dotnet
          key: ${{ runner.os }}-build-dotnet-6.0.102
          restore-keys: |
            ${{ runner.os }}-build-dotnet-6.0.102

      - name: Setup .NET
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: "6.x"
          include-prerelease: true

      - uses: actions/setup-java@v2.5.0
        with:
          distribution: "adopt"
          java-version: "11"
          check-latest: true

      - name: Install tools
        run: |
          dotnet workload restore
        # dotnet workload install android ios maccatalyst tvos macos maui wasm-tools
        
      - name: Restore dependencies
        run: dotnet restore
      # - name: Build
      #   run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore
