name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  uses: Thuyen21/Blazor-Movie-/.github/workflows/setup.yml@test-action
    with:
      username: ${{ inputs.username }}
      token: ${{ secrets.token }}
  build:
    runs-on: windows-2022
    steps:

      # - name: Build
      #   run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore
