name: Deploy

on:
  push:
    branches: [main]

jobs:
  Publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-quality: "preview"

      - name: Setup Java
        uses: actions/setup-java@v3.11.0
        with:
          distribution: "adopt"
          java-version: "11"
          check-latest: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install tools
        run: |
          # dotnet workload restore
          dotnet workload install android ios maccatalyst tvos macos maui wasm-tools wasm-experimental
          # dotnet workload install wasm-tools wasm-experimental

      - name: Publish
        working-directory: "./BlazorMovie/Server/"
        run: dotnet publish BlazorMovie.Server.csproj

      - name: copy file
        run: copy "./Dockerfile" "./BlazorMovie/Server/bin/Debug/net7.0/publish/"

      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: publish
          path: "./BlazorMovie/Server/bin/Debug/net7.0/publish/"

  Deploy:
    needs: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.NAME}}
          heroku_email: ${{secrets.EMAIL}}
          usedocker: true
          justlogin: true

      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: publish
          path: "./BlazorMovie/Server/bin/Debug/net7.0/publish/"

      - name: Deploy
        working-directory: "./BlazorMovie/Server/bin/Debug/net7.0/publish/"
        run: |
          heroku container:login
          heroku container:push web -a movie213
          heroku container:release web -a movie213
